name: climetlab installs

on: pull_request

jobs:
  install-climetlab:  # Installs climetlab on various OS.
    name: Install climetlab, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: import climetlab
      run: |
        python -c "import climetlab"

  install-conda-climetlab:
    name: install-conda-climetlab
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
    - name: Set up conda environment
      run: |
          conda create --name climetlab-dev python=3.7 xarray
          conda activate climetlab-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: import climetlab
      run: |
        which python
        python -c "import climetlab"
